"use strict";
// shrinking guest list;u jst found out that ur new dinner table won't arrive in timefor the dinner ,n u have space for only two guests.
// add a new line that print a message saying that u can invite only 2 people for the dinner.
let list6 = ["niece", "sister", "cousin", "friend", "neighbour", "Sana", "Ali", "Hina", "friend2"];
console.log(list6["0"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["1"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["2"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["3"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["4"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["5"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["6"], `"i am exteremely sorry that i can invite only two people"`);
console.log(list6["7"], `"i am exteremely sorry that i can invite only two people"`);
list6.pop();
console.log(list6);
console.log("friend2 :unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("Hina :unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("Ali :unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("sana:unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("neighbour:unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("friend:unfortunately! the bigger table what i found won't available on time.so better luck next time");
list6.pop();
console.log("cousin:unfortunately! the bigger table what i found won't available on time.so better luck next time");
console.log(list6);
console.log("niece", `"my dear niece u r still invited"`);
console.log("sister", `"my dear sister u r still invited"`);
list6.pop();
list6.pop();
console.log(list6);
